### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by florianpeninon** [chibatching/select_all_slices#1]
Just trying to test the plugin and it's not working at all. Nothing happen on Sketch, not even an error :/

**Comment by chibatching** [comment]
Does plugin appear on menu? Would you show me your layer list screenshot?

**Comment by florianpeninon** [comment]
Hmm, I think I misunderstood the plugin. It doesn't select layers with an export option but only the slices?

**Comment by chibatching** [comment]
Yes, this plugin support only slice now. But, it seems good to select exportable layer. I'll try in the next version.

**Comment by chibatching** [comment]
I released select all exportable layers as v2.0.
